name: Call Reusable_WF

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment Value'
        type: environment
        required: true

jobs:
  call-workflow:
    uses: aps-Github-DevOps/reusable_wf/.github/workflows/diff_env_call.yml@main
    with: 
      environment: ${{ inputs.environment }}
      secrets: inherit