name: Call Reusable_WF

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment Value'
        type: environment
        required: true

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    environment: "${{ github.event.inputs.environment }}"
    steps:
     - uses: aps-Github-DevOps/reusable_wf/.github/workflows/diff_env_call.yml@main
       with: 
        environment: ${{ inputs.environment }}
        ENV_USERNAME: ${{ secrets.ENV_USERNAME }}
        ENV_PASS: ${{ secrets.ENV_PASS }}