name: Manual Different_Env

on: 
  workflow_dispatch:

jobs:
  
  DEV:
    runs-on: ubuntu-latest
    environment: dev
    env:
      ENV_USERNAME: ${{ secrets.ENV_USERNAME }}
      ENV_PASS: ${{ secrets.ENV_PASS }}
    
    if: ENV_USERNAME == 'DEV_User'

    steps:
      - name: Checks-out
        uses: actions/checkout@v3

      - name: Print Details
        run: |
          echo "I am running in Dev environment"
          echo "User Name: $ENV_USERNAME Pass: $ENV_PASS"

  QA:
    runs-on: ubuntu-latest
    environment: QA
    needs: DEV
    env:
      ENV_USERNAME: ${{ secrets.ENV_USERNAME }}
      ENV_PASS: ${{ secrets.ENV_PASS }}

    steps:
      - name: Checks-out
        uses: actions/checkout@v3

      - name: Print Details
        run: |
          echo "I am running in QA environment"
          echo "User Name: $ENV_USERNAME Pass: $ENV_PASS"

  PERF:
    runs-on: ubuntu-latest
    environment: PERF
    needs: QA
    env:
      ENV_USERNAME: ${{ secrets.ENV_USERNAME }}
      ENV_PASS: ${{ secrets.ENV_PASS }}

    steps:
      - name: Checks-out
        uses: actions/checkout@v3

      - name: Print Details
        run: |
          echo "I am running in PERF environment"
          echo "User Name: $ENV_USERNAME Pass: $ENV_PASS"