name: Call Reusable_WF

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment Value'
        type: environment
        required: true

jobs:
  call-workflow:
    uses: 
      runs-on: ubuntu-latest
      
      steps:
      - name: Send greeting
        run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
